### ISSUE TITLE
Replay for site redirecting to a different URL not working

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was-pywb#95] opened 2022-07-08 14:25 UTC
Content does not replay for https://swap.stanford.edu/was/20170127002327/http://www.jean-luc-melenchon.fr/ 
pywb shows the header and a blank frame.

Does replay at: https://swap.stanford.edu/was/20170127002327/http://www.melenchon.fr/

Openwayback redirects from http://www.jean-luc-melenchon.fr/ to http://www.melenchon.fr: 
https://sul-swap-prod.stanford.edu/20170127002317/http://jean-luc-melenchon.fr/ 
but pywb does not do this. 

Captures listed in sul-embed for the seed http://jean-luc-melenchon.fr/ go to a blank page: https://searchworks.stanford.edu/view/gv741ns3784

May require looking at the level3.cdxj index to find the WARC files at play. For read-only access to indexes, use the was-dev VM.

**Comment by lwrubel** [comment] 2022-07-08 15:10
Here's a WARC to inspect (from druid https://argo.stanford.edu/view/druid:pq295wn4399)

ARCHIVEIT-6838-MONTHLY-JOB303556-20170527051544576-00008.warc.gz

**Comment by mjgiarlo** [comment] 2022-07-21 18:16
We wonder if this might be related to, or the same as, #64

**Comment by justinlittman** [comment] 2022-07-21 19:17
```
WARC/1.0^M
WARC-Type: revisit^M
WARC-Target-URI: http://www.jean-luc-melenchon.fr/^M
WARC-Date: 2017-05-27T00:23:08Z^M
WARC-IP-Address: 37.59.26.212^M
WARC-Profile: http://netpreserve.org/warc/1.0/revisit/identical-payload-digest^M
WARC-Truncated: length^M
WARC-Refers-To-Target-URI: http://s-www.bienpublic.com/robots.txt^M
WARC-Refers-To-Date: 2016-02-27T00:24:07Z^M
WARC-Payload-Digest: sha1:K4QYYMLLNEQ6FTLBAJ5CHB7NYMNC3FDR^M
WARC-Refers-To: <urn:uuid:b92c9ef9-6840-45c3-953a-20b2a07d7255>^M
WARC-Record-ID: <urn:uuid:5d7f97cc-043b-44d3-936f-0a493cd80b2f>^M
Content-Type: application/http; msgtype=response^M
Content-Length: 341^M
^M
HTTP/1.1 301 Moved Permanently^M
Server: nginx^M
Date: Sat, 27 May 2017 00:23:09 GMT^M
Content-Type: text/html^M
Content-Length: 3^M
Connection: close^M
Expires: Thu, 19 Nov 1981 08:52:00 GMT^M
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0^M
Pragma: no-cache^M
Location: http://melenchon.fr^M
X-Powered-By: PleskLin^M
```

**Comment by justinlittman** [comment] 2022-07-21 19:22
In https://github.com/sul-dlss/was-pywb/issues/64#issuecomment-1166379069, @edsu says:
> Given a revisit, pywb will look by digest sha1QH732FYSV7UM34JYWVYMB7EZGR2CYM6B to find a matching non-revisit record.

However, for this URL all of the records are revisit records. (I've verified this by grepping both the CDX and CDXJ indices.)

**Comment by justinlittman** [comment] 2022-07-21 19:29
@edsu @lwrubel thoughts?

**Comment by lwrubel** [comment] 2022-07-21 20:08
Helpful to hear the results of grepping the index, @justinlittman. Is this in one of the collections where there were WARCs we still need to accession? It's sounding like we don't have the original record, which seems strange.

**Comment by justinlittman** [comment] 2022-07-21 20:13
This seems to be from an older collection the preceded WRA: https://argo.stanford.edu/view/druid:tr960gh0976

As such, it was not evaluated for remediation.

**Comment by lwrubel** [comment] 2022-07-21 20:48
@peterchanws would you agree we should audit this collection?

**Comment by lwrubel** [comment] 2022-07-21 20:49
Oh, realizing that we can't if it's not in WRA so would need a different approach, am I understanding that correctly, @justinlittman?

**Comment by justinlittman** [comment] 2022-07-21 21:11
The audit task would need some minor enhancements to support auditing collections that are not in WRA.

**Comment by lwrubel** [comment] 2022-07-22 12:40
Next step is to audit the collection, once work on https://github.com/sul-dlss/was-registrar-app/issues/504 is done.

**Comment by edsu** [comment] 2022-07-22 15:12
Justin were you not able to find a response record for `http://melenchon.fr` in the CDX files located in `sul-swap-prod.stanford.edu:/web-archiving-stacks/data/indices/cdx/`? I think it *must* be in there for https://sul-swap-prod.stanford.edu/20170127002317/http://melenchon.fr/ to be working?

I wonder if this is pointing to some kind of problem during our indexing, either a WARC file that was missed, or was not readable by cdxj-indexer? If we can locate the WARC file that contains the response record we could look in our new CDXJ indexes to see if that WARC file was indexed.

**Comment by edsu** [comment] 2022-07-22 15:21
Just a heads up: I'm running these to get the CDX entries that mention `melenchon.fr`in the old openwayback and new pywb indexes:

on `sul-swap-prod`:
```
grep 'melenchon.fr' /web-archiving-stacks/data/indices/cdx/*.cdx > melenchon.fr.cdx
```

on `was-pywb-prod`:
```
grep 'melenchon.fr' /web-archiving-stacks/data/indexes/cdxj/*.cdxj > melenchon.fr.cdxj
```

**Comment by edsu** [comment] 2022-07-22 19:55
I was worried that the WARC response records for `https://melenchon.fr/` weren't indexed. Fortunately the indexes for both openwayback and pywb contain 1,273,628 entries that mention melenchon.fr. And I can see that https://melenchon.fr itself does [play back](https://swap.stanford.edu/was/*?url=https%3A%2F%2Fmelenchon.fr). So the issue is why doesn't it redirect properly?

**Comment by edsu** [comment] 2022-07-22 21:03
I see this in the WARC spec for the [Identical-Payload-Digest](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#profile-identical-payload-digest) revisit profile, which is at play here:

---

Using a WARC-Refers-To header to identify a specific prior record from which the matching content can be retrieved is recommended, to minimize the risk of misinterpreting the ‘revisit’ record. The following two optional fields can also be used to associate the revisit record with the original record. Their use is recommended:

* WARC-Refers-To-Target-URI. Its value should be equal to the WARC-Target-URI in the WARC record that the current record is considered a duplicate of.
* WARC-Refers-To-Date. Its value should be equal to the WARC-Date in the WARC record that the current record is considered a duplicate of.

---

But if you look at the revisit record that @justinlittman pasted above it has a `WARC-Refers-To-Target-URI: http://s-www.bienpublic.com/robots.txt`. So pywb might be looking that URL up in the index and there's only one response record for that, and finds:

```
was@was-pywb-prod:~$ warcio extract /web-archiving-stacks/data/collections/tr960gh0976/yq/494/dn/7895/ARCHIVEIT-6838-MONTHLY-JOB198346-20160227002330935-00000.warc.gz 10150269
WARC/1.0
WARC-Type: response
WARC-Target-URI: http://s-www.bienpublic.com/robots.txt
WARC-Date: 2016-02-27T00:24:07Z
WARC-IP-Address: 145.226.119.23
WARC-Payload-Digest: sha1:K4QYYMLLNEQ6FTLBAJ5CHB7NYMNC3FDR
WARC-Record-ID: <urn:uuid:b92c9ef9-6840-45c3-953a-20b2a07d7255>
Content-Type: application/http; msgtype=response
Content-Length: 330

HTTP/1.1 200 OK
Date: Sat, 27 Feb 2016 00:24:08 GMT
Server: Apache
Last-Modified: Mon, 27 Jan 2014 08:28:24 GMT
Cache-Control: public, max-age=86400
Content-Length: 3
Expires: Sat, 27 Feb 2016 14:22:37 GMT
Access-Control-Allow-Origin: *
Vary: Accept-Encoding
Age: 36091
Connection: close
Content-Type: text/plain
```

Which is an empty text document which is what we are seeing?  

Perhaps pywb respects  the `WARC-Refers-To-Target-URI` header when looking up a response record and our version of OpenWayback did not?

**Comment by edsu** [comment] 2022-07-22 21:22
It does seem like the `WARC-Refers-To-Target-URI` will be used to look up the record:

https://github.com/webrecorder/pywb/blob/main/pywb/warcserver/resource/resolvingloader.py#L193-L196

**Comment by lwrubel** [comment] 2022-07-25 13:52
That's some great digging to figure out what's happening here. I wonder why the WARC-Refers-to-Target-URI goes to that robots.txt file. Is that the part that looks like a bug?

I'm curious why this site works in Archive-It--maybe it is also handling WARC-Refers-To-Target-URI differently?

**Comment by lwrubel** [comment] 2022-07-27 14:03
Ruled out that we are missing any WARCs by using the rake audit task on WRA.

**Comment by justinlittman** [comment] 2022-07-27 17:39
We aren't missing WARCs in the collection. However, it isn't clear when AIT crawls whether it handles revisits globally or for a collection. That is, perhaps AIT has the original record but it isn't in a WARC that is part of the collection.

**Comment by lwrubel** [comment] 2022-07-27 18:39
One wrinkle here is that the content redirects correctly in Openwayback and we're using the same set of WARCs.

**Comment by justinlittman** [comment] 2022-07-27 18:44
You'll notice in the [comment above](https://github.com/sul-dlss/was-pywb/issues/95#issuecomment-1191845160) that the revisit record has a response body which includes the redirect information. One theory is that Openwayback reads this (and therefore can correctly redirect), but PyWB does not.

**Closed** 2022-09-06 16:17 UTC
Labels: bug, web archiving, blocked, replay
